### ISSUE TITLE
Dynamic routes possible?

### ISSUE THREAD

**Issue by Lazymondaysunday** [sneas/react-nested-routes-example#21]
This is a super awesome implementation of react router, is there anyway to make it work with dynamic routes? Especially the breadcrumb path/url.

**Comment by sneas** [comment]
Hi @Lazymondaysunday. Thank you for your kind words. I don't think this implementation will work with dynamic routing because this implementation assumes having nested navigation, but nested navigation isn't possible with dynamic routing.

If I'd need dynamic routes + breadcrumbs, I'd probably use Context API to manage breadcrumbs.
